image: mcr.microsoft.com/dotnet/sdk:5.0

stages:
    - test
    - build

test:
    stage: test
    script:
        - "dotnet test"

build:
    stage: build
    script:
        - "dotnet build"
    artifacts:
      paths:
        - bin/
